### ISSUE TITLE
arch support for dracut

### ISSUE THREAD

**Issue by CuriousRubick** [johnfanv2/LenovoLegionLinux#107]
Can we update the LenovoLegionLinux.hook to support dracut? Below is an example of how Endeavouros supports both mkinitcpio and dracut when updating nvidia drivers.

https://github.com/endeavouros-team/PKGBUILDS/tree/master/nvidia-hook

**Comment by johnfanv2** [comment]
This topic falls within @MrDuartePT realm of expertise and experience. What is the benefit of it @CuriousRubick and do you want to create a pull request for it?

**Comment by MrDuartePT** [comment]
@CuriousRubick i implement on this [commit](f087da8d958ac2f7a7ad81bfbb4f4de0f39e4dbb) and update the aur
