### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by MasterKia** [johnfanv2/LenovoLegionLinux#116]
Hi, I was wondering if the current driver is in good shape and whether you plan on upstreaming it to Linux.

> _[I want to get it merged into the mainline Linux kernel, so this is not needed anymore. So please star this repository :)](https://github.com/johnfanv2/LenovoLegionLinux#permanent-install-instruction)_

**Comment by johnfanv2** [comment]
There are 4 main points:
- implementing all the features of the 2022 and 2023 in the same interface
- finishing implementing fan curve in custom mode in 2022 and 2023 models
- fixing all the bugs
- refactoring and making consistent with ideapad driver

**Comment by MrDuartePT** [comment]
I will close this issue since is nothing to discuss here yet.
In the future we can reopen this when the driver is ready for upstream
