### ISSUE TITLE
DOES THIS WORK FOR : LEGION 7i (7-15IMH05  - Type 81YT )

### ISSUE THREAD

**Issue by waelb2** [johnfanv2/LenovoLegionLinux#121]
I recently installed Ubuntu and I'm having some issues such as ACPI BIOS

**Comment by waelb2** [comment]
> You should provide details and actual errors.

![IMG_20230912_005642.jpg](https://github.com/johnfanv2/LenovoLegionLinux/assets/105824672/93f9d52d-f02c-4a28-ae83-1f4c4daa4140)

**Comment by MrDuartePT** [comment]
This is not a repo focus on solving problems when instaling linux.
Pls use the legion discord server for that or just google your problem
