### ISSUE TITLE
[BUG] 21J8 Lenovo ThinkBook 16p Gen 4 Has no sound for speakers

### ISSUE THREAD

**Issue by levihuayuzhang** [johnfanv2/LenovoLegionLinux#125]
**Model and Debug Info**

Distribution: Arch Linux x86_64 
Model name: 21J8 Lenovo ThinkBook 16p Gen 4
CPU model: 13th Gen Intel i9-13900H (20) @ 5.200GHz
GPU model: NVIDIA GeForce RTX 4060 Max-Q / Mobile

Alsa info output: http://alsa-project.org/db/?f=c01609fa968a44856b46e7aad41be6b96269f59e

The Cirrus AMP cs35l41 seems has not configured to work with the Sound Card.

Thus, the matrix of speakers not work functionly: the upper speakers sound volume is extremly low and downside (bass) speaker has no sound.

**Comment by MrDuartePT** [comment]
Sorry but you are using a lenovo thinkpad not a lenovo legion, and this kernel driver dont aims to solve hardware problems, only aims to give support for LLT and Lenovo Vantage feature on Linux.

Pls use the bugzilla forum or Lenovo comunity forum to discuss this topic.
