### ISSUE TITLE
[BUG] python3-darkdetect package is missing in Fedora repos

### ISSUE THREAD

**Issue by MasterKia** [johnfanv2/LenovoLegionLinux#131]
The [requirements](https://github.com/johnfanv2/LenovoLegionLinux#requirements) section suggests installing the `python3-darkdetect` package but it's not available on the Fdeora repos.

Therefore the Python GUI doesn't use the dark theme, maybe add a manual toggle in settings for dark mode?

**Comment by MrDuartePT** [comment]
If you use the fedora repo available here you will not have that problem
https://github.com/johnfanv2/LenovoLegionLinux/tree/main/package_repo

**Comment by MrDuartePT** [comment]
well you have to option download the rpm manually every update or not use the python package and dont have both gui and cli.
It very dificult process to get package accept in fedora repos, that why fedora copr and rpm fusion exist.
But for now i will not upload "pre-release" package to fedora copr
