### ISSUE TITLE
[Legion Slim 5 16APH8] Can't set up the LLL tool on EOS 

### ISSUE THREAD

**Issue by bogatav** [johnfanv2/LenovoLegionLinux#144]
**Problem Description**
Hello!
Trying to setup the LLL on my Legion Slim 5 16APH8 (2023) but getting the error "egion: probe of PNP0C09:00 failed with error -5" after "sudo make reloadmodule" [step](https://github.com/johnfanv2/LenovoLegionLinux#build-and-test-instruction).

**Model and Debug Info**

Distribution: EndeavourOS (on 27.11.2023).
Model: 82Y90044ID
Processor: AMD Ryzen™ 7 7840HS Processor(Ryzen™ 7 7840HS)
Graphics: NVIDIA® GeForce RTX™ 4060 8GB
Keyboard backlight: RGB
Light in lid or logo: no
Light at IO-Ports at back: no (power only)

[dmesg_out.log](https://github.com/johnfanv2/LenovoLegionLinux/files/13474110/dmesg_out.log)

Glad to help with tests on my machine.
In case of any qustion ping me here, via email: a.v.bogatyrenko@gmail.com or via Telegram: @bogatav

**Comment by MrDuartePT** [comment]
Hello!
I think that dmesg output is incomplete and pls fell a new Issue with full bug report including the dmidecode command.
