### ISSUE TITLE
how to remove incase if i dont like it?

### ISSUE THREAD

**Issue by DOOMMARINE117** [johnfanv2/LenovoLegionLinux#154]
HI, i have installed it. will this work for legion go handheld?

if i dont like it.

how t remove it in debian?

**Comment by Rexcrazy804** [comment]
@DOOMMARINE117 
[Refer this section of the readme](https://github.com/johnfanv2/LenovoLegionLinux?tab=readme-ov-file#uninstall-instruction)

**Comment by MrDuartePT** [comment]
Thanks for the answer
