### ISSUE TITLE
Reset to defaults

### ISSUE THREAD

**Issue by Flashwalker** [johnfanv2/LenovoLegionLinux#172]
**Is your feature request related to a problem? Please describe.**
If settings are applied incorrectly, it should be possible to reset the settings to the default state they were in before application
ref: https://github.com/johnfanv2/LenovoLegionLinux/issues/171#issuecomment-1974685571

**Comment by Flashwalker** [comment]
Is there a way i can reset to defaults?

**Comment by MrDuartePT** [comment]
Pls don’t make duplicates. I gonna answer on the other issue
