### ISSUE TITLE
Update gentoo guru ebuild

### ISSUE THREAD

**Issue by st0nie** [johnfanv2/LenovoLegionLinux#181]
https://pastebin.com/0Tc49VFi

CC @MrDuartePT

**Comment by st0nie** [comment]
cc @MrDuartePT

**Comment by st0nie** [comment]
https://github.com/gentoo/guru/pull/153

**Comment by MrDuartePT** [comment]
Also you can't take out sed or RBUILD is requirement since is use to change the version string.

**Comment by MrDuartePT** [comment]
But thanks for notice the missing die in the ebuild. Also I gonna remeve the `make reloadmodule` I have put in the ebuild but is not good pratice

**Comment by st0nie** [comment]
> Also you can't take out sed or RBUILD is requirement since is use to change the version string.

I mean `sed` package is in system-sets , like gcc
U can use `eix --system` to check that

**Comment by MrDuartePT** [comment]
Yha I know but exist other ebuild that also add sed when doing subtituion

**Comment by MrDuartePT** [comment]
Also systemd require acpi event are not part of acpi flag. Because the acpi event in the folder was trying to make the mission button to work. And also set balance mode as the default when plug in the charger.
I also thinking of drop that one from the ebuild and aur package

**Comment by st0nie** [comment]
https://github.com/gentoo/guru/commit/e9ec4a0db0f62974d327d8bb1633667fd455a531#r139720787

**Comment by st0nie** [comment]
> Also systemd require acpi event are not part of acpi flag. Because the acpi event in the folder was trying to make the mission button to work. And also set balance mode as the default when plug in the charger. I also thinking of drop that one from the ebuild and aur package

We can drop acpid useflag because it is required by `legiond`, just install all the events file into `/usr/share/...`

**Comment by MrDuartePT** [comment]
> > Also systemd require acpi event are not part of acpi flag. Because the acpi event in the folder was trying to make the mission button to work. And also set balance mode as the default when plug in the charger. I also thinking of drop that one from the ebuild and aur package
> 
> We can drop acpid useflag because it is required by `legiond`, just install all the events file into `/usr/share/...`

I doing that part using the systemd useflag and just add acpid package to there

**Comment by st0nie** [comment]
> I doing that part using the systemd useflag and just add acpid package to there
The "systemd" use flag should not be used to determine whether service files are installed. According to official standards, if both OpenRC scripts and systemd services are available, they should be installed unconditionally.

**Comment by st0nie** [comment]
Just keep the `acpi` and `gui` useflag enable by default
User need a good default value

**Comment by MrDuartePT** [comment]
> Just keep the `acpi` and `gui` useflag enable by default if `acpi` use is enabled, install all the acpid files into `/usr/share` and install `legion_ppd` and`legion_ac` into /etc/acpid/events User need a good default value

That have a little problem it break the daemon funcionalty I think we just make acpid part of the gui since is require for it

**Comment by MrDuartePT** [comment]
Some user I know that use the gui also use the daemon so it better to not break the install

**Comment by st0nie** [comment]
> Some user I know that use the gui also use the daemon so it better to not break the install. I also have to see a way to add openrc support to the daemon. Since it only two service.

Well, I think once our OpenRC service is ready, we can remove the use of systemd and install both sets of init service files.

**Comment by st0nie** [comment]
> Some user I know that use the gui also use the daemon so it better to not break the install. I also have to see a way to add openrc support to the daemon. Since it only two service.

https://forums.gentoo.org/viewtopic-p-8813895.html?sid=05052e14289f0e63a8413e0cc21f51cb

use elogind seems ok

**Comment by st0nie** [comment]
Emm, I think we can simplify it even further because I haven't seen many packages with such complex USE flags. We can directly simplify it to three USE flags: gui, downgrade-nvidia, and elogind. We can handle other dependencies using the optfeature eclass.

**Comment by st0nie** [comment]
> Well if you have that ideia try to do it and see if works. I can give a look to end of the day, have other work to do.

Thank you && Have a good day at work.

**Comment by st0nie** [comment]
https://github.com/weBj8/webj8-overlay/blob/main/sys-firmware/lenovolegionlinux/lenovolegionlinux-9999.ebuild

Done openrc script

**Comment by MrDuartePT** [comment]
Thanks, just one thing why you dont ask acess to the guru overlay and help me mantain the package

**Comment by MrDuartePT** [comment]
@st0nie nice work if you can clone guru and upload here the patch/diff file (no need for PR on guru I then commit it in dev branch), just for you to be the author of the commit.

**Comment by st0nie** [comment]
> @st0nie nice work (I have looked at the ebuild now with more detailed).
> 
> If you can clone guru and upload here the patch/diff file (no need for PR on guru I then commit it in dev branch), just for you to be the author of the commit.

https://pastebin.com/mMAEMwd9

**Comment by MrDuartePT** [comment]
Well diff dosent perserve the commiter. Also updated the changes to guru now

**Comment by MrDuartePT** [comment]
@st0nie 
https://github.com/gentoo/guru/actions/runs/8315885277/job/22754725631
I think you need to ask acess for the guru overlay if not I will have to remove your email:

Just open a Bug in the Buzilla asking acess to the guru overlay saying you what to help mantain LLL. I will then ask someone to add you.
