### ISSUE TITLE
Touchpad enabled option doesn't untick when it is disabled

### ISSUE THREAD

**Issue by aadish151** [johnfanv2/LenovoLegionLinux#19]
Hi,

I'm using this utility with Legion 5 Pro 16ACH6H (AMD 5800H + Nvidia RTX 3070) on PopOS (22.04 LTS with kernel 6.0.12-76060006-generic). Everything works as expected. Thanks for this awesome utility! I found this visual bug where the touchpad enabled option doesn't untick when it is disabled. Functionally it works as expected by turning on/off the touchpad. This issue also only happens in the currently opened session i.e. if I close the GUI and open it again, the touchpad enabled option is unticked.

Screencast of the issue:
[Screencast from 02-19-2023 12:54:47 AM.webm](https://user-images.githubusercontent.com/43163551/219933884-b0079b21-e6a4-4d09-9825-afdf6b8472ae.webm)

**Comment by johnfanv2** [comment]
Thanks a lot for testing and the feedback.  I added your model to the list of compatible models. I really appreciate your thorough testing! 

It seems like the effect when setting the touchpad is not immediate after setting it. So the value was read back to early. I hope I have fixed it in the new version that I have pushed. I hope that you can test it.

**Comment by aadish151** [comment]
Thanks for the quick fix! Yes, now the touchpad enabled option unticks as expected. Keep up the great work 👍
