### ISSUE TITLE
Could this project support windows?

### ISSUE THREAD

**Issue by rango886** [johnfanv2/LenovoLegionLinux#198]
Could this project support windows?

**Comment by st0nie** [comment]
You can use the official Lenovo legion center application on windows

**Comment by rango886** [comment]
my laptop is r9000k 2021, official Lenovo legion center not support fan control

**Comment by rango886** [comment]
I use this project on ubuntu r9000k 2021, this project can control fan speed

**Comment by st0nie** [comment]
Use legionfancontrol

**Comment by rango886** [comment]
I have tried legionfancontrol, but its fan control logic is different from LenovoLegionLinux. While legionfancontrol has set up fan curves, when the CPU load suddenly increases, the fan speeds up abruptly and then drops back to the set value. On the other hand, LenovoLegionLinux, tested on Ubuntu, maintains a stable fan curve control regardless of load fluctuations.

legionfancontrol struggles to effectively control the fan; the fan tends to intermittently make sudden noise, which is quite annoying.

**Comment by rango886** [comment]
legionfancontrol is closed-source, and I cannot make changes to it. I have tried decompiling legionfancontrol, but I found that I couldn't understand the decompiled code. I looked at the code of this project, but I don't have much knowledge of Linux programming, so I also find it difficult to understand.

**Comment by rango886** [comment]
I've written a command-line tool that supports controlling fan speed on Windows !!! https://github.com/rango886/LegionFanEmbeddedController
