### ISSUE TITLE
[BUG] repository 'https://johnfanv2.github.io/LenovoLegionLinux/package_repo/ubuntu ./ Release' no longer has a Release file

### ISSUE THREAD

**Issue by mcarans** [johnfanv2/LenovoLegionLinux#217]
**Problem Description**
I get this error when updating in my package manager:

E: The repository 'https://johnfanv2.github.io/LenovoLegionLinux/package_repo/ubuntu ./ Release' no longer has a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.

**Model and Debug Info**

Distribution: Kubuntu 23.10
Model name: Legion Slim 5 14

**Comment by MrDuartePT** [comment]
I deleted the ppa repo, now all user should use the debian package: https://tracker.debian.org/pkg/lenovolegionlinux
