### ISSUE TITLE
help pls 

### ISSUE THREAD

**Issue by archuserbtw2** [johnfanv2/LenovoLegionLinux#22]
i accidentally installed the app and messed up the whole fan curve how can i set it back to normal how it was before 
current config 

EC Chip ID: 8227
EC Chip Version: 2a4
legion_laptop version: 0.1
legion_laptop features: fancurve powermode platformprofile platformprofilenotify minifancurve
legion_laptop ec_readonly: 0
minifancurve feature enabled: 1
minifancurve on cool: false
lock fan controller: true
enable maximumfanspeed: error
enable maximumfanspeed status: -1
fan curve current point id: 0
fan curve points size: 4
Current fan curve in hardware (embedded controller):
rpm1|rpm2|acceleration|deceleration|cpu_min_temp|cpu_max_temp|gpu_min_temp|gpu_max_temp|ic_min_temp|ic_max_temp
0	 0	 2	 2	 0	 0	 0	 127	 0	 37
1800	 1800	 2	 2	 0	 35	 127	 127	 33	 40
2400	 2400	 2	 2	 35	 45	 127	 127	 37	 43
2800	 2800	 2	 2	 45	 59	 127	 127	 40	 43
=====================

please send me a good config or how to reset it in basic ways since its been only 1 moth i startes using ubuntu

**Comment by johnfanv2** [comment]
Just press Ctrl+Q to change the power mode. It will reset it, whenever you change it. It looks like you have enabled "mini fancurve" because it only has 4 entries. You might want to experiment with disabling it.
