### ISSUE TITLE
修复 Legion Y9000X 2022 IAH7 内置扬声器在 Linux 下无声音的问题

### ISSUE THREAD

**Issue by fb0sh** [johnfanv2/LenovoLegionLinux#229]
这有一篇参考文章，他的patch是否可以合并到linux kernel主线呢
https://alampy.com/2024/04/13/fix-legion-y9000x-2022-iah7-speaker-on-linux/
麻烦您看一下

**Comment by pzc1350** [comment]
arch下作者已提交 dkms
yay -S legion-y9000x-2022-iah7-sound-fix-dkms
