### ISSUE TITLE
kernel patch for 6.11

### ISSUE THREAD

**Issue by i-am-logger** [johnfanv2/LenovoLegionLinux#267]
getting this error with the nix package

![image](https://github.com/user-attachments/assets/4d2c7707-a7f3-44d2-90e9-c06550cf568c)

**Comment by MrDuartePT** [comment]
The issue was solve in commit 61f05e082afe2af9fec3d038e8c800192b2de07f.

It also seems that nixos update there package, next time before reporting a bug upstream try the latest master. 
This was a downtream bug.
