### ISSUE TITLE
Create a simple script to patch the kernel for simplicity

### ISSUE THREAD

**Issue by ARYN-27** [johnfanv2/LenovoLegionLinux#28]
Including a simple script in `LenovoLegionLinux/kernel_module` for kernel patch could ease the use since Arch has constant kernel update compared to the rest. 

```bash
#!/bin/bash

make
sudo make install
sudo make reloadmodule | tail -n 5 | bat
sudo systemctl restart power-profiles-daemon

echo "Done"
```

**Comment by johnfanv2** [comment]
Thanks, for the patch!
