### ISSUE TITLE
Legion 5 15ARH05 | `Failed to start Apply Fan Curve` boot error message

### ISSUE THREAD

**Issue by juba0x00** [johnfanv2/LenovoLegionLinux#30]
```
systemd[1]: Failed to start Apply Fan Curve to Lenovo Legion Laptop depending of Power State and Charger Mode (LenovoLegionLinux kernel Module).
```
- this error appears every time I powerup the laptop 
- I'm using Manjaro Linux

![image](https://user-images.githubusercontent.com/73611543/228030739-1219993c-4f80-4bae-9b06-6021687a62ee.png)

**Comment by johnfanv2** [comment]
@MrDuartePT What does this could mean?

**Comment by MrDuartePT** [comment]
This error in not warmfull at all in some distro that happen because the service will load before the kernel module. The service will reload when you change the porwer profile.

**Comment by juba0x00** [comment]
@MrDuartePT Sorry, I don't know about this project.
I have a new Legion 5 laptop, I used the program for I small time I found some problems but I don't sure if this problem is from the program, One of these is Fn + Q shortcut does not work.
I'll test it again and keep in touch with you.
Thank you for helping.

**Comment by MrDuartePT** [comment]
If you update the kernel you need to reinstall the LenovoLegionLinux package I will create a pacman hook to do that. If you reinstall the package pls reload the systemd service manually

**Comment by juba0x00** [comment]
@MrDuartePT 
everything is working perfectly, Thank you for this great project
I have a question if you don't mind
The [legion-fan-utils-linux project](https://github.com/MrDuartePT/legion-fan-utils-linux) is not recommended or included in the documentation, so I don't know what I will miss if I don't use it.

**Comment by MrDuartePT** [comment]
The only thing the project do is a simple manner of creating fan profiles and apply it and also change between profiles when you change the power mode (queit, balance and performance) both on battery and charger. Me and @Petingoso only made it because we what a more quiet profile on quiet more and a more aggressive curve on peformance and to be persistent across reboot.
