### ISSUE TITLE
Energy Curve Control

### ISSUE THREAD

**Issue by lrmpsm53** [johnfanv2/LenovoLegionLinux#31]
Hello. I have a lenovo legion s7 16arha7 laptop. I wanted to manage power consumption settings to reduce heat and improve battery life. Is it possible now? If not, what can I do to help make this possible?

**Comment by johnfanv2** [comment]
I guess you want to control you CPU or GPU. This is stuff for the CPU driver/controller programs: maybe this helps https://wiki.archlinux.org/title/CPU_frequency_scaling . Otherwise, try the discord chat. I have seen many people with ridiculous low power consumption there.

**Comment by lrmpsm53** [comment]
No. I'm interested in the power management of the processor. Reducing the frequency did not reduce heat generation. I am currently researching this topic.

**Comment by johnfanv2** [comment]
Do you know if this function is available on Windows? What tools are used there?
