### ISSUE TITLE
missing fan curve presets for GUI

### ISSUE THREAD

**Issue by staniboy** [johnfanv2/LenovoLegionLinux#34]
Whenever I try to load a present from gui I get 
`  File "/home/ms-dos/LenovoLegionLinux/python/legion_linux/legion.py", line 49, in load_from_file
    with open(filename, 'r', encoding=DEFAULT_ENCODING) as filepointer:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/legion_linux/performance-ac.yaml'
`
GUI tool ran with sudo.

edit: on GUI start I get this in terminal: 
`QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Create path /root/.config/legion_linux
`

Sorry for a dumb question (I am new to this kind of stuff) but how do I get the curve presets after module install? It seems that my laptop works on 1/3 power of what it used to. I get 1/3 of hashrate on XMRig regardless of the power plan. I did all the quick tests and they all seemed to pass...
It seems that instead of spinning fans it throttling cpu down? 

It seems better after the reset
My curve read out after hard reset(60 seconds power button method):

rpm1|rpm2|acceleration|deceleration|cpu_min_temp|cpu_max_temp|gpu_min_temp|gpu_max_temp|ic_min_temp|ic_max_temp
0	 0	 5	 5	 0	 54	 0	 62	 0	 37
1500	 1800	 5	 5	 50	 54	 59	 62	 33	 40
1600	 2000	 5	 5	 50	 54	 59	 62	 37	 43
1700	 2200	 5	 5	 50	 54	 59	 62	 40	 127
1900	 2400	 2	 2	 50	 64	 59	 62	 127	 127
2400	 2800	 2	 2	 58	 68	 59	 67	 127	 127
2600	 3000	 2	 2	 64	 73	 62	 72	 127	 127
3300	 3600	 2	 2	 68	 78	 67	 75	 127	 127
3300	 3900	 2	 2	 73	 82	 72	 78	 127	 127
4500	 4500	 2	 2	 78	 127	 75	 127	 127	 127

But still it seems as it throttling down instead of going over 60C temperature. 
Running on: 
Legion 5 17ITH6H (82JM002LRU)
BIOS: H1CN52WW 
OS: Ubuntu 20.04

edit: As I understand those presets are the curves used by Fn+Q modes? When I press Fn + Q it seems that curve does not gets updated (I assume because those presets are missing?) I will try to look into the problem myself but please let me know if you know why this could be happening.

**Comment by johnfanv2** [comment]
Thanks for the bug report. I guess I have not implemented a good error message first. 

I assume that you first have to save a preset before you can load it. Do you still have the problem when you save a preset before loading it?

Regarding the throttling: Please check the fan speed with psensor when the CPU is under load. Does the fan speed goes to the set values, e.g. 3300 or 4500 rpm? If the fan speed goes to the set values the fans seems to be ok. Then, the problem might be the power profile of the CPU or GPU which is unrelated to this tool.

Currently, the tool does not set the profiles when you switch with Fn + Q. Instead Fn + Q will use the default fan curves programmed inside the hardware. This might be a feature for the future. There is also the tool https://github.com/MrDuartePT/legion-fan-utils-linux, which does it.

**Comment by staniboy** [comment]
The problem was due to "thermald" package so removing it resolved the issue with throttling. I did uninstalled the module before since performance was pretty low even without it :D. 

One thing I noticed last time however is that if I read curve from HW after pressing Fn + Q the curve appears the same in gui (without a change). Another thing is when I press to write to HW (same curve that I just read) it will write it back to HW differently. 

I will reinstall the module and will provide some actual information if this is still a case.

**Comment by staniboy** [comment]
The only question would be is disabling termald would be safe? It seems that processor can run pretty hot at silent mode (98C) in sensors

**Comment by johnfanv2** [comment]
Regarding thermald and overheating. 

Please check that the fans are really controlled according to the fan curve. Please check the fan speed and temperatures with psensor when the CPU is under load. Does the fan speed goes to the set values, e.g. 3300 or 4500 rpm?
You can accidentially "lock the fan controller". In this case, it will always keep the same speed.
```bash
sudo stress --cpu 10 --timeout 200
```
If I run the above command to put 10 out of 12 threads on my AMD system under load the temperature reaches 65 degrees before the fans turn on. With the fans it stays at 55 degrees under load (quiet mode). Do you reach 98 degrees with fans running? I guess this is a hardware problem. Maybe not enough heat paste or something like that.

**Comment by staniboy** [comment]
My Legion have Intel i7 11800h so things here could be way different. Curve does work fine in balanced and performance. Fans kick in just when they should. Quite mode curve works fine as far as fans go but  the CPU without thermald gets borderline hot. With it enabled everything is quite since thermald plays it safe and underclocks the CPU before it gets the chance to get hot enough to step up fans. Even with stress test it keeps it at the bay. 

Unfortunately I'm not too savvy in linux type of things :( The best I can do is to provide you with outputs / run commands.

I found this on thermal_deamon github, might explain something... to you... I am clueless :man_shrugging: 
https://github.com/intel/thermal_daemon/issues/323

**Comment by staniboy** [comment]
also seems like someone else have the same issue with this processor on Gentoo
https://github.com/intel/thermal_daemon/issues/350

**Comment by johnfanv2** [comment]
Hm. Looks interesting. Thanks for confirming that my module works on 22.10. Is there any problem left?

Regarding thermlad, what you can try is the following:
* Disable/remove the legion kernel module and run only with thermald: Then thermald should not know in which power mode the laptop is. I guess it will use the last known setting. So if if disable the legion module in performance, thermald might always run it until 95C regardless of mode.
* Check what happens if you also disable thermald.
