### ISSUE TITLE
nixos support 

### ISSUE THREAD

**Issue by realsnick** [johnfanv2/LenovoLegionLinux#81]
Hi,

Will be happy to help with testing for Legion 7i Pro 2023. I might need some mentoring on loading the kernel module in nixos (its different)

**Comment by realsnick** [comment]
will be good to load this module here : https://github.com/NixOS/nixos-hardware/pull/660

**Comment by ulrikstrid** [comment]
The kernel module is packaged for NixOS already, I'm not at my computer but can send a snippet later on how to activate it

**Comment by ulrikstrid** [comment]
Sorry for the delay, did not have my computer during the weekend, but it should be as easy as this:
```nix
  boot.extraModulePackages = [ config.boot.kernelPackages.lenovo-legion-module ];
```
